services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: "edxapp"
      MYSQL_USER: "edxapp001"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: mysql-entrypoints.d
        target: /docker-entrypoint-initdb.d/
        read_only: true
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: 'edxapp'
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: mongo-entrypoints.d
        target: /docker-entrypoint-initdb.d/
        read_only: true
  memcache:
    image: memcached
    ports:
      - 11211:11211
